Nodejs-week3 warmup initial commit
agkabir/hyf-homework pull request #22
Opened 2023-02-16 13:17 UTC by agkabir

2023-02-16 21:09 UTC, itsgauravsaxena requested changes
Did you try sql injection demo and record it?

2023-02-16 21:09 UTC, itsgauravsaxena commented on nodejs/week3/app.js
> +const port = process.env.PORT;
You should add PORT in .env file else port will be undefined

2023-02-16 21:09 UTC, itsgauravsaxena commented on nodejs/week3/.env.example
> +DB_PORT = db_port
Missing PORT

2023-02-17 07:58 UTC, agkabir commented on nodejs/week3/app.js
> +const port = process.env.PORT;
I have PORT defined in .env file. By mistake I forgot to write it on .env.example

2023-02-17 07:58 UTC, agkabir commented on nodejs/week3/.env.example
> +DB_PORT = db_port
Yes. you are right. but I have it in .env

2023-02-20 18:10 UTC, merged